문자열 계산기 리팩토링
hyojhand/java-baseball-playground pull request #7
Opened 2023-01-10 16:19 UTC by hyojhand

### 내용
branch step2에서 구현한 문자열 계산기를 리팩토링한다.

2023-01-12 14:51 UTC, hyunssooo requested changes
몇 가지 코멘트 남겼습니다. 
확인 부탁 드려요.

2023-01-12 14:51 UTC, hyunssooo commented on src/main/java/stringcalculator/Calculator.java
> +    }
메서드명과 메서드의 동작이 일치하나요?
메서드명은 숫자인지 검사를 하는 것 같은데 실제로는 검사 + 숫자로 변경 두가지 일을 하고 있지 않나요?

2023-01-12 14:51 UTC, hyunssooo commented on src/main/java/stringcalculator/Calculator.java
> +
배열보다 List, Set 과 같은 컬렉션에 익숙해 지는 것이 좋습니다. 학습해 보면 좋을 것 같아요.

2023-01-12 14:51 UTC, hyunssooo commented on src/main/java/stringcalculator/Operator.java
> +public enum Operator {
이 클래스의 테스트는 존재하지 않네요?

2023-01-12 16:34 UTC, hyojhand commented on src/main/java/stringcalculator/Calculator.java
> +    }
메서드명과 동일한 하나의 기능을 하도록 리팩토링했습니다.

리팩토링 과정에서, 메서드에서 숫자 체크 후 결과를 boolean으로 return하고 호출한 메서드에서 예외를 처리하도록 하였고,
default 접근제어자로 변경하여 해당 메서드의 테스트도 작성했습니다.

위와 다르게 해당 메서드에서 숫자가 아니라면 바로 예외를 처리하는 방법 중에 고민입니다.

2023-01-13 14:54 UTC, hyunssooo approved these changes
몇 가지 코멘트 남겼습니다. 
다음 step 진행하시면서 참고 부탁드려요~

2023-01-13 14:54 UTC, hyunssooo commented on src/main/java/stringcalculator/Calculator.java
> +
테스트를 위해 접근제어자를 변경하는 것에 좋을까요? 어떻게 생각하시나요?

2023-01-13 14:54 UTC, hyunssooo commented on src/main/java/stringcalculator/Calculator.java
> +
복수형으로 변수명을 정하는게 더 좋을 것 같아요. 
관심사는 리스트가 아닌 내부에 있는 String이 아닐까요?

2023-01-13 14:54 UTC, hyunssooo commented on src/main/java/stringcalculator/Calculator.java
> +
split 라는 변수명은 도움이 될까요?

2023-01-13 14:54 UTC, merged