숫자야구게임 리팩토링
hyojhand/java-baseball-playground pull request #9
Opened 2023-01-23 11:25 UTC by hyojhand

## 기능 요구 사항
기본적으로 1부터 9까지 서로 다른 수로 이루어진 3자리의 수를 맞추는 게임이다.

- 같은 수가 같은 자리에 있으면 스트라이크, 다른 자리에 있으면 볼, 같은 수가 전혀 없으면 포볼 또는 낫싱이란 힌트를 얻고, 그 힌트를 이용해서 먼저 상대방(컴퓨터)의 수를 맞추면 승리한다.
e.g. 상대방(컴퓨터)의 수가 425일 때, 123을 제시한 경우 : 1스트라이크, 456을 제시한 경우 : 1볼 1스트라이크, 789를 제시한 경우 : 낫싱
- 위 숫자 야구 게임에서 상대방의 역할을 컴퓨터가 한다. 컴퓨터는 1에서 9까지 서로 다른 임의의 수 3개를 선택한다. 게임 플레이어는 컴퓨터가 생각하고 있는 3개의 숫자를 입력하고, 컴퓨터는 입력한 숫자에 대한 결과를 출력한다.
- 이 같은 과정을 반복해 컴퓨터가 선택한 3개의 숫자를 모두 맞히면 게임이 종료된다.
- 게임을 종료한 후 게임을 다시 시작하거나 완전히 종료할 수 있다.

2023-01-24 12:22 UTC, hyunssooo requested changes
몇 가지 코멘트 남겼습니다~ 
같이 고민해 보아요.

2023-01-24 12:22 UTC, hyunssooo commented on src/main/java/baseballrefactor/controller/GameController.java
> +
이 필드는 필요한가요? 요구 사항을 풀어내기 위해서 Controller 필드에 존재하면 동시성 이슈는 없을까요?

2023-01-24 12:22 UTC, hyunssooo commented on src/main/java/baseballrefactor/domain/Ball.java
> +        }
int 값이 숫자가 아닐 경우도 있나요?

2023-01-24 12:22 UTC, hyunssooo commented on src/main/java/baseballrefactor/domain/Ball.java
> +
order 는 필요한가요??

2023-01-24 12:22 UTC, hyunssooo commented on src/main/java/baseballrefactor/domain/Ball.java
> +
balls 내부 List에 이미 순서가 있지 않나요? List 의 index와 ball의 order는 다른가요?

2023-01-24 12:22 UTC, hyunssooo commented on src/main/java/baseballrefactor/domain/Balls.java
> +    }
보통 getter는 클래스 하단에 존재합니다.
메서드 순서도 고민해 보면 좋을 것 같아요.

2023-01-24 12:22 UTC, hyunssooo commented on src/main/java/baseballrefactor/domain/Balls.java
> +    }
메서드명은 Check 인데 리턴값이 List 인 것은 어색하지 않나요?

2023-01-24 12:22 UTC, hyunssooo commented on src/main/java/baseballrefactor/domain/BaseBallGame.java
> +    }
굳이 메서드 분리한 이유가 있나요?

2023-01-24 12:22 UTC, hyunssooo commented on src/main/java/baseballrefactor/domain/GameResult.java
> +    }
setter는 제거해 볼 수 없을까요?

2023-01-24 12:22 UTC, hyunssooo commented on src/main/java/baseballrefactor/domain/GameResult.java
> +    }
메서드 순서에 대해서 학습해 보아요.

2023-01-24 12:22 UTC, hyunssooo commented on src/main/java/baseballrefactor/domain/GenerateNumber.java
> +        return numbers;
1 ~ 9 까지는 생성이 자주 일어날 것 같은데 한 번 만들어 두고 재사용하는 방법은 어떨까요? 

```java
private static final List<Integer> NUMBERS = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9);

// 사용법 
Collections.shuffle(NUMBERS);
NUMBERS.stream()
    .limit(3)
    .collect(Collectors.toList());
```
`List.of()` 를 사용하지 못 하는 이유는 무엇일까요?

2023-01-24 12:22 UTC, hyunssooo commented on src/main/java/baseballrefactor/domain/GenerateNumber.java
> +        return numbers;
stream은 연산마다 개행을 주면 가독성을 높일 수 있습니다.

2023-01-24 12:22 UTC, hyunssooo commented on src/test/java/baseballrefactor/domain/BaseballGameTest.java
> +        Assertions.assertThat(gameResult.getStrikeCount()).isEqualTo(1);
```suggestion

        assertThat(gameResult.getBallCount()).isEqualTo(0);
        assertThat(gameResult.getStrikeCount()).isEqualTo(1);
```

`org.junit.jupiter.api.Assertions#assertAll` 도 찾아보고 적용해 보아요.

2023-01-24 16:24 UTC, hyojhand commented on src/main/java/baseballrefactor/controller/GameController.java
> +
인스턴스 변수로 변경했습니다.

2023-01-24 16:25 UTC, hyojhand commented on src/main/java/baseballrefactor/domain/Ball.java
> +        }
사용자가 문자로 입력했을 경우를 생각했는데,
Ball 객체를 만드는 생성자 에서는 고려하지 않아도 될 것 같아 숫자의 범위만 확인하도록 수정했습니다.

2023-01-24 16:26 UTC, hyojhand commented on src/main/java/baseballrefactor/domain/Ball.java
> +
Balls 클래스의 compareResult 메서드는 balls와 ball을 비교하는 메서드로,
비교하는 ball의 index를 알기위해 해당 볼의 위치를 표현하는 order를 사용했습니다.

2023-01-24 16:33 UTC, hyojhand commented on src/main/java/baseballrefactor/domain/Balls.java
> +    }
일반적인 메서드 순서를 고려하여 리팩토링 했습니다.

추가로 메서드 순서 관련하여, Balls 클래스의 생성자 아래에 어떤 메서드가 먼저 오는 것이 좋을지 고민입니다.
1. 생성자에서 호출한 changeBalls, getValidateNumbers 메서드를 호출한 메서드 아래에 위치하여 가독성을 높이는 방법
2. 핵심 로직인 compareResult 메서드를 생성자 아래에 위치시키는 방법

어떤 접근이 더 좋은지 궁금합니다.

2023-01-24 16:34 UTC, hyojhand commented on src/main/java/baseballrefactor/domain/Balls.java
> +    }
메서드 작명에 더 신경써야겠네요.
검증된 숫자들을 반환하는 getValidateNumbers로 변경해봤습니다.

2023-01-24 16:34 UTC, hyojhand commented on src/main/java/baseballrefactor/domain/BaseBallGame.java
> +    }
불필요한 분리로 삭제했습니다.

2023-01-24 16:36 UTC, hyojhand commented on src/main/java/baseballrefactor/domain/GameResult.java
> +    }
3번의 스트라이크로 게임이 종료되는 테스트 코드를 작성하는 과정에서
기존의 reportCount() 메서드로 strike를 3번 반복하는 과정이 비효율적이라 생각했고,
이를 setter로 strikecount를 수정하기위한 의도로 사용했는데,
테스트 코드를 위해 setter를 열어놓은게 실수인 것 같네요.

setter 삭제와 함께 테스트 코드도 리팩토링 했습니다.

2023-01-24 16:38 UTC, hyojhand commented on src/main/java/baseballrefactor/domain/GenerateNumber.java
> +        return numbers;
만들어 두고 shuffle 이후 3개만 사용하는 방법을 생각못했네요.
굳이 distinct로 중복제거해줄 필요도 없어 좋은것 같습니다!

List.of()는 불변 객체를 생성하기 때문에, 변경할 수 없으며 UnsupportedOperationException을 발생시킵니다.

2023-01-24 16:39 UTC, hyojhand commented on src/test/java/baseballrefactor/domain/BaseballGameTest.java
> +        Assertions.assertThat(gameResult.getStrikeCount()).isEqualTo(1);
assertAll로 리팩토링 했습니다.

2023-01-25 13:53 UTC, hyunssooo approved these changes
수고하셨습니다~

2023-01-25 13:53 UTC, hyunssooo commented on src/main/java/baseballrefactor/domain/GameResult.java
> +    private int strikeCount = 0;
이 클래스는 불변 객체로 만들어 볼 수 없을까요?

2023-01-25 13:53 UTC, hyunssooo commented on src/main/java/baseballrefactor/domain/Ball.java
> +
index 를 외부에서 알고 있는데 ball 내부에서 알 필요가 있을까 싶네요. 순서에 대한 책임이 ball 내부에서 관리해야 할까요?

2023-01-25 13:53 UTC, merged